@startuml c
left to right direction
skinparam backgroundColor #0000
skinparam actorStyle stick
skinparam usecase {
  BackgroundColor #1E1E1E
  BorderColor black
  ArrowColor black
  FontColor white
}
skinparam actor {
  BackgroundColor black
  BorderColor black
  FontColor black
}

actor Empleador

rectangle "C.U Empleador" {
    Empleador --> (Registrar empresa en la plataforma)
    (Registrar empresa en la plataforma) .> (Validar existencia de la empresa) : <<include>>

    Empleador --> (Publicar trabajo)
    (Publicar trabajo) .> (Crear publicación de trabajo) : <<include>>
    (Publicar trabajo) .> (Especificar fecha de la publicación) : <<include>>
    (Publicar trabajo) .> (Editar y eliminar publicación) : <<include>>
    (Publicar trabajo) .> (Elegir modalidad de trabajo) : <<extend>>
    (Publicar trabajo) .> (Subir fotos del lugar) : <<extend>>

    Empleador --> (Buscar trabajadores)
    (Buscar trabajadores) .> (Filtrar trabajadores según disponibilidad) : <<include>>
    (Buscar trabajadores) .> (Ver trabajadores cercanos a la ubicación) : <<extend>>
    (Buscar trabajadores) .> (Aplicar filtros de confianza) : <<extend>>
}
@enduml
