@startuml Diagrama de Procesos
start

:Registrar Cliente;
:Iniciar Sesión;

if (¿Publicar trabajo?) then (sí)
  :Cliente publica trabajo;
  :Trabajo queda disponible;
else
endif

if (¿Trabajador postula?) then (sí)
  :Trabajador postula a trabajo;
  :Cliente elige trabajador;
else
endif

:Se realiza trabajo;

if (¿Evaluar trabajo?) then (sí)
  :Cliente genera estadísticas;
else
endif

if (¿Problema con trabajo?) then (sí)
  :Cliente o Empleador realiza denuncia;
  :Denuncia es gestionada por Gestor;
  :Gestor asigna a Abogado;
  :Abogado investiga y reporta;
else
endif

:Administrador valida denuncias;
stop
@enduml
